spring:
  application:
    name: product-service

server:
  port:  6104
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.1.2:6200/eureka